e apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  labels:
    app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}{{ .Values.nameSuffix }}
